overrides:
  vite@*: npm:@voidzero-dev/vite-plus-core@1.0.0
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  esbuild: true
  workerd: true
patchedDependencies:
  "@aiden0z/pptx-renderer@1.3.0": patches/@aiden0z__pptx-renderer@1.3.0.patch
